fix compile err due to Tab characters are not allowed
Fix below compile error:
ERROR: /home/liujg6/localrepo/malmo/vendor_new/kernel_platform/vendor/qcom/opensource/camera-kernel/camera_modules.bzl:258:2: Tab characters are not allowed for indentation. Use spaces instead.

Change-Id: I83cf5d1c0410c33f7cb4ac383f2648358db43a76
Reviewed-on: https://gerrit.mot.com/2820423
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Submit-Approved: Jira Key
Tested-by: Jira Key
Reviewed-by: Qiong Xie <xieq2@motorola.com>